### ISSUE TITLE
Link given is not working

### ISSUE THREAD

**Issue by ramrattle** [aws-samples/aws-deepcomposer-samples#1]
The link provided is not working,also deepcomposer is not showing up on aws console

**Comment by phmagic** [comment]
hi @ramrattle DeepComposer is still in limited preview so searching on the AWS console will not work.

The DeepComposer console is only available to workshop participants during the week of re:Invent. We're opening up access soon.  Please sign up for the preview here:
https://aws.amazon.com/deepcomposer/
